language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t manas5996/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true manas5996/docker-react npm run test